// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: admin.proto

package distkvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle is whether a node is currently participating in consensus.
type Lifecycle int32

const (
	Lifecycle_LIFECYCLE_UNSPECIFIED Lifecycle = 0
	// RUNNING: the Raft node exists and is ticking.
	Lifecycle_LIFECYCLE_RUNNING Lifecycle = 1
	// CRASHED: the Raft node has been torn down and its storage closed.
	// Its durable state is untouched and Restart recovers from it.
	Lifecycle_LIFECYCLE_CRASHED Lifecycle = 2
)

// Enum value maps for Lifecycle.
var (
	Lifecycle_name = map[int32]string{
		0: "LIFECYCLE_UNSPECIFIED",
		1: "LIFECYCLE_RUNNING",
		2: "LIFECYCLE_CRASHED",
	}
	Lifecycle_value = map[string]int32{
		"LIFECYCLE_UNSPECIFIED": 0,
		"LIFECYCLE_RUNNING":     1,
		"LIFECYCLE_CRASHED":     2,
	}
)

func (x Lifecycle) Enum() *Lifecycle {
	p := new(Lifecycle)
	*p = x
	return p
}

func (x Lifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_proto_enumTypes[0].Descriptor()
}

func (Lifecycle) Type() protoreflect.EnumType {
	return &file_admin_proto_enumTypes[0]
}

func (x Lifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lifecycle.Descriptor instead.
func (Lifecycle) EnumDescriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

type FollowerProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextIndex     uint64                 `protobuf:"varint,1,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`
	MatchIndex    uint64                 `protobuf:"varint,2,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowerProgress) Reset() {
	*x = FollowerProgress{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowerProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerProgress) ProtoMessage() {}

func (x *FollowerProgress) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerProgress.ProtoReflect.Descriptor instead.
func (*FollowerProgress) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *FollowerProgress) GetNextIndex() uint64 {
	if x != nil {
		return x.NextIndex
	}
	return 0
}

func (x *FollowerProgress) GetMatchIndex() uint64 {
	if x != nil {
		return x.MatchIndex
	}
	return 0
}

type NodeStatus struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Lifecycle Lifecycle              `protobuf:"varint,2,opt,name=lifecycle,proto3,enum=distkv.Lifecycle" json:"lifecycle,omitempty"`
	// role is "follower", "candidate", or "leader"; empty while crashed.
	Role              string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Term              uint64 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId          string `protobuf:"bytes,5,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CommitIndex       uint64 `protobuf:"varint,6,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	LastApplied       uint64 `protobuf:"varint,7,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	LastLogIndex      uint64 `protobuf:"varint,8,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LogLen            uint64 `protobuf:"varint,9,opt,name=log_len,json=logLen,proto3" json:"log_len,omitempty"`
	LastIncludedIndex uint64 `protobuf:"varint,10,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	LastIncludedTerm  uint64 `protobuf:"varint,11,opt,name=last_included_term,json=lastIncludedTerm,proto3" json:"last_included_term,omitempty"`
	// followers is the leader's nextIndex/matchIndex bookkeeping, keyed by
	// peer id. It is empty on a node that isn't leader.
	Followers map[string]*FollowerProgress `protobuf:"bytes,12,rep,name=followers,proto3" json:"followers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// isolated_from names the peers this node is currently refusing to
	// exchange Raft traffic with, in both directions — a simulated network
	// partition, not a change of membership.
	IsolatedFrom []string `protobuf:"bytes,13,rep,name=isolated_from,json=isolatedFrom,proto3" json:"isolated_from,omitempty"`
	// key_count is how many keys the state machine currently holds, and
	// uptime_ms how long the current incarnation of the node has been
	// running (reset by Crash/Restart, not by leader changes).
	KeyCount      uint64 `protobuf:"varint,14,opt,name=key_count,json=keyCount,proto3" json:"key_count,omitempty"`
	UptimeMs      uint64 `protobuf:"varint,15,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *NodeStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeStatus) GetLifecycle() Lifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return Lifecycle_LIFECYCLE_UNSPECIFIED
}

func (x *NodeStatus) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NodeStatus) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *NodeStatus) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *NodeStatus) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *NodeStatus) GetLastApplied() uint64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *NodeStatus) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *NodeStatus) GetLogLen() uint64 {
	if x != nil {
		return x.LogLen
	}
	return 0
}

func (x *NodeStatus) GetLastIncludedIndex() uint64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *NodeStatus) GetLastIncludedTerm() uint64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *NodeStatus) GetFollowers() map[string]*FollowerProgress {
	if x != nil {
		return x.Followers
	}
	return nil
}

func (x *NodeStatus) GetIsolatedFrom() []string {
	if x != nil {
		return x.IsolatedFrom
	}
	return nil
}

func (x *NodeStatus) GetKeyCount() uint64 {
	if x != nil {
		return x.KeyCount
	}
	return 0
}

func (x *NodeStatus) GetUptimeMs() uint64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

type SetPartitionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// peers is the complete set this node should refuse traffic with,
	// replacing any previous set. An empty list heals the node.
	Peers         []string `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPartitionRequest) Reset() {
	*x = SetPartitionRequest{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPartitionRequest) ProtoMessage() {}

func (x *SetPartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPartitionRequest.ProtoReflect.Descriptor instead.
func (*SetPartitionRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *SetPartitionRequest) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

type LifecycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleRequest) Reset() {
	*x = LifecycleRequest{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleRequest) ProtoMessage() {}

func (x *LifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleRequest.ProtoReflect.Descriptor instead.
func (*LifecycleRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

type LifecycleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lifecycle     Lifecycle              `protobuf:"varint,1,opt,name=lifecycle,proto3,enum=distkv.Lifecycle" json:"lifecycle,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleReply) Reset() {
	*x = LifecycleReply{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleReply) ProtoMessage() {}

func (x *LifecycleReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleReply.ProtoReflect.Descriptor instead.
func (*LifecycleReply) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *LifecycleReply) GetLifecycle() Lifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return Lifecycle_LIFECYCLE_UNSPECIFIED
}

func (x *LifecycleReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\x06distkv\"R\n" +
	"\x10FollowerProgress\x12\x1d\n" +
	"\n" +
	"next_index\x18\x01 \x01(\x04R\tnextIndex\x12\x1f\n" +
	"\vmatch_index\x18\x02 \x01(\x04R\n" +
	"matchIndex\"\xed\x04\n" +
	"\n" +
	"NodeStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\tlifecycle\x18\x02 \x01(\x0e2\x11.distkv.LifecycleR\tlifecycle\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x05 \x01(\tR\bleaderId\x12!\n" +
	"\fcommit_index\x18\x06 \x01(\x04R\vcommitIndex\x12!\n" +
	"\flast_applied\x18\a \x01(\x04R\vlastApplied\x12$\n" +
	"\x0elast_log_index\x18\b \x01(\x04R\flastLogIndex\x12\x17\n" +
	"\alog_len\x18\t \x01(\x04R\x06logLen\x12.\n" +
	"\x13last_included_index\x18\n" +
	" \x01(\x04R\x11lastIncludedIndex\x12,\n" +
	"\x12last_included_term\x18\v \x01(\x04R\x10lastIncludedTerm\x12?\n" +
	"\tfollowers\x18\f \x03(\v2!.distkv.NodeStatus.FollowersEntryR\tfollowers\x12#\n" +
	"\risolated_from\x18\r \x03(\tR\fisolatedFrom\x12\x1b\n" +
	"\tkey_count\x18\x0e \x01(\x04R\bkeyCount\x12\x1b\n" +
	"\tuptime_ms\x18\x0f \x01(\x04R\buptimeMs\x1aV\n" +
	"\x0eFollowersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.distkv.FollowerProgressR\x05value:\x028\x01\"\x0f\n" +
	"\rStatusRequest\"+\n" +
	"\x13SetPartitionRequest\x12\x14\n" +
	"\x05peers\x18\x01 \x03(\tR\x05peers\"\x12\n" +
	"\x10LifecycleRequest\"W\n" +
	"\x0eLifecycleReply\x12/\n" +
	"\tlifecycle\x18\x01 \x01(\x0e2\x11.distkv.LifecycleR\tlifecycle\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*T\n" +
	"\tLifecycle\x12\x19\n" +
	"\x15LIFECYCLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LIFECYCLE_RUNNING\x10\x01\x12\x15\n" +
	"\x11LIFECYCLE_CRASHED\x10\x022\xf5\x01\n" +
	"\x05Admin\x123\n" +
	"\x06Status\x12\x15.distkv.StatusRequest\x1a\x12.distkv.NodeStatus\x12?\n" +
	"\fSetPartition\x12\x1b.distkv.SetPartitionRequest\x1a\x12.distkv.NodeStatus\x129\n" +
	"\x05Crash\x12\x18.distkv.LifecycleRequest\x1a\x16.distkv.LifecycleReply\x12;\n" +
	"\aRestart\x12\x18.distkv.LifecycleRequest\x1a\x16.distkv.LifecycleReplyB.Z,github.com/sujalbistaa/DistKV/proto/distkvpbb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_admin_proto_goTypes = []any{
	(Lifecycle)(0),              // 0: distkv.Lifecycle
	(*FollowerProgress)(nil),    // 1: distkv.FollowerProgress
	(*NodeStatus)(nil),          // 2: distkv.NodeStatus
	(*StatusRequest)(nil),       // 3: distkv.StatusRequest
	(*SetPartitionRequest)(nil), // 4: distkv.SetPartitionRequest
	(*LifecycleRequest)(nil),    // 5: distkv.LifecycleRequest
	(*LifecycleReply)(nil),      // 6: distkv.LifecycleReply
	nil,                         // 7: distkv.NodeStatus.FollowersEntry
}
var file_admin_proto_depIdxs = []int32{
	0, // 0: distkv.NodeStatus.lifecycle:type_name -> distkv.Lifecycle
	7, // 1: distkv.NodeStatus.followers:type_name -> distkv.NodeStatus.FollowersEntry
	0, // 2: distkv.LifecycleReply.lifecycle:type_name -> distkv.Lifecycle
	1, // 3: distkv.NodeStatus.FollowersEntry.value:type_name -> distkv.FollowerProgress
	3, // 4: distkv.Admin.Status:input_type -> distkv.StatusRequest
	4, // 5: distkv.Admin.SetPartition:input_type -> distkv.SetPartitionRequest
	5, // 6: distkv.Admin.Crash:input_type -> distkv.LifecycleRequest
	5, // 7: distkv.Admin.Restart:input_type -> distkv.LifecycleRequest
	2, // 8: distkv.Admin.Status:output_type -> distkv.NodeStatus
	2, // 9: distkv.Admin.SetPartition:output_type -> distkv.NodeStatus
	6, // 10: distkv.Admin.Crash:output_type -> distkv.LifecycleReply
	6, // 11: distkv.Admin.Restart:output_type -> distkv.LifecycleReply
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		EnumInfos:         file_admin_proto_enumTypes,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
