// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: kv.proto

package distkvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op int32

const (
	Op_OP_UNSPECIFIED Op = 0
	Op_OP_GET         Op = 1
	Op_OP_PUT         Op = 2
	Op_OP_APPEND      Op = 3
	Op_OP_DELETE      Op = 4
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_GET",
		2: "OP_PUT",
		3: "OP_APPEND",
		4: "OP_DELETE",
	}
	Op_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"OP_GET":         1,
		"OP_PUT":         2,
		"OP_APPEND":      3,
		"OP_DELETE":      4,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

// Command is both a client request and, marshaled as-is, the payload
// proposed to the Raft log: the same bytes a client sends are what the
// state machine later decodes when applying the committed entry.
//
// client_id must be a value the client generates once per session (e.g.
// a random token) and seq_no must increase by exactly 1 with every
// request sent in that session, including Get. The state machine uses
// (client_id, seq_no) to deduplicate retried Put/Append/Delete requests
// and to let a client tell whether the entry that landed at the log index
// its request was assigned is really its own request or a different
// leader's request that overwrote it after a failover.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SeqNo         uint64                 `protobuf:"varint,2,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`
	Op            Op                     `protobuf:"varint,3,opt,name=op,proto3,enum=distkv.Op" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Command) GetSeqNo() uint64 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *Command) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_OP_UNSPECIFIED
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CommandReply struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Value   string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Found   bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"` // for Get: whether the key existed
	Error   string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// leader_hint is set when success is false because this node isn't
	// leader; it names the node the client should retry against, if known.
	LeaderHint string `protobuf:"bytes,5,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	// index is the log index this request was committed at, on a successful
	// reply from a leader. It is not part of the state machine's answer —
	// it exists so a caller can point at exactly where in the replicated log
	// its request landed.
	Index         uint64 `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandReply) Reset() {
	*x = CommandReply{}
	mi := &file_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReply) ProtoMessage() {}

func (x *CommandReply) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReply.ProtoReflect.Descriptor instead.
func (*CommandReply) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{1}
}

func (x *CommandReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CommandReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CommandReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandReply) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

func (x *CommandReply) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type SessionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNo         uint64                 `protobuf:"varint,1,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`
	Reply         *CommandReply          `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionState) Reset() {
	*x = SessionState{}
	mi := &file_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionState) ProtoMessage() {}

func (x *SessionState) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionState.ProtoReflect.Descriptor instead.
func (*SessionState) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{2}
}

func (x *SessionState) GetSeqNo() uint64 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *SessionState) GetReply() *CommandReply {
	if x != nil {
		return x.Reply
	}
	return nil
}

// Snapshot is the KV state machine's entire state, as passed to and from
// raft.Node.Snapshot/delivered on ApplyCh's SnapshotValid messages.
type Snapshot struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Data          map[string]string        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sessions      map[string]*SessionState `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{3}
}

func (x *Snapshot) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Snapshot) GetSessions() map[string]*SessionState {
	if x != nil {
		return x.Sessions
	}
	return nil
}

var File_kv_proto protoreflect.FileDescriptor

const file_kv_proto_rawDesc = "" +
	"\n" +
	"\bkv.proto\x12\x06distkv\"\x81\x01\n" +
	"\aCommand\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x15\n" +
	"\x06seq_no\x18\x02 \x01(\x04R\x05seqNo\x12\x1a\n" +
	"\x02op\x18\x03 \x01(\x0e2\n" +
	".distkv.OpR\x02op\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\"\xa1\x01\n" +
	"\fCommandReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1f\n" +
	"\vleader_hint\x18\x05 \x01(\tR\n" +
	"leaderHint\x12\x14\n" +
	"\x05index\x18\x06 \x01(\x04R\x05index\"Q\n" +
	"\fSessionState\x12\x15\n" +
	"\x06seq_no\x18\x01 \x01(\x04R\x05seqNo\x12*\n" +
	"\x05reply\x18\x02 \x01(\v2\x14.distkv.CommandReplyR\x05reply\"\x82\x02\n" +
	"\bSnapshot\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.distkv.Snapshot.DataEntryR\x04data\x12:\n" +
	"\bsessions\x18\x02 \x03(\v2\x1e.distkv.Snapshot.SessionsEntryR\bsessions\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aQ\n" +
	"\rSessionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.distkv.SessionStateR\x05value:\x028\x01*N\n" +
	"\x02Op\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06OP_GET\x10\x01\x12\n" +
	"\n" +
	"\x06OP_PUT\x10\x02\x12\r\n" +
	"\tOP_APPEND\x10\x03\x12\r\n" +
	"\tOP_DELETE\x10\x042\xc2\x01\n" +
	"\x02KV\x12,\n" +
	"\x03Get\x12\x0f.distkv.Command\x1a\x14.distkv.CommandReply\x12,\n" +
	"\x03Put\x12\x0f.distkv.Command\x1a\x14.distkv.CommandReply\x12/\n" +
	"\x06Append\x12\x0f.distkv.Command\x1a\x14.distkv.CommandReply\x12/\n" +
	"\x06Delete\x12\x0f.distkv.Command\x1a\x14.distkv.CommandReplyB.Z,github.com/sujalbistaa/DistKV/proto/distkvpbb\x06proto3"

var (
	file_kv_proto_rawDescOnce sync.Once
	file_kv_proto_rawDescData []byte
)

func file_kv_proto_rawDescGZIP() []byte {
	file_kv_proto_rawDescOnce.Do(func() {
		file_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)))
	})
	return file_kv_proto_rawDescData
}

var file_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kv_proto_goTypes = []any{
	(Op)(0),              // 0: distkv.Op
	(*Command)(nil),      // 1: distkv.Command
	(*CommandReply)(nil), // 2: distkv.CommandReply
	(*SessionState)(nil), // 3: distkv.SessionState
	(*Snapshot)(nil),     // 4: distkv.Snapshot
	nil,                  // 5: distkv.Snapshot.DataEntry
	nil,                  // 6: distkv.Snapshot.SessionsEntry
}
var file_kv_proto_depIdxs = []int32{
	0, // 0: distkv.Command.op:type_name -> distkv.Op
	2, // 1: distkv.SessionState.reply:type_name -> distkv.CommandReply
	5, // 2: distkv.Snapshot.data:type_name -> distkv.Snapshot.DataEntry
	6, // 3: distkv.Snapshot.sessions:type_name -> distkv.Snapshot.SessionsEntry
	3, // 4: distkv.Snapshot.SessionsEntry.value:type_name -> distkv.SessionState
	1, // 5: distkv.KV.Get:input_type -> distkv.Command
	1, // 6: distkv.KV.Put:input_type -> distkv.Command
	1, // 7: distkv.KV.Append:input_type -> distkv.Command
	1, // 8: distkv.KV.Delete:input_type -> distkv.Command
	2, // 9: distkv.KV.Get:output_type -> distkv.CommandReply
	2, // 10: distkv.KV.Put:output_type -> distkv.CommandReply
	2, // 11: distkv.KV.Append:output_type -> distkv.CommandReply
	2, // 12: distkv.KV.Delete:output_type -> distkv.CommandReply
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_kv_proto_init() }
func file_kv_proto_init() {
	if File_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kv_proto_goTypes,
		DependencyIndexes: file_kv_proto_depIdxs,
		EnumInfos:         file_kv_proto_enumTypes,
		MessageInfos:      file_kv_proto_msgTypes,
	}.Build()
	File_kv_proto = out.File
	file_kv_proto_goTypes = nil
	file_kv_proto_depIdxs = nil
}
